name: Multi-Environment Deploy

on:
  push:
    branches:
      - main  # Untuk Prod
      - dev   # Untuk Dev (Kita akan buat branch ini nanti)

jobs:
  deploy-pintar:
    name: Deploy ke AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Terraform Init
      run: terraform init

    - name: Pilih Workspace Otomatis
      run: |
        # Mengambil nama branch saat ini (main atau dev)
        BRANCH_NAME=${{ github.ref_name }}
        
        # Logika Mapping:
        # Jika branch 'main', kita pakai workspace 'prod'
        # Jika branch 'dev', kita pakai workspace 'dev'
        
        if [ "$BRANCH_NAME" == "main" ]; then
          WORKSPACE_NAME="prod"
        else
          WORKSPACE_NAME="dev"
        fi
        
        echo "Branch saat ini: $BRANCH_NAME"
        echo "Target Workspace: $WORKSPACE_NAME"
        
        # Select workspace, kalau belum ada, create baru
        terraform workspace select $WORKSPACE_NAME || terraform workspace new $WORKSPACE_NAME

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve